# SPDX-FileCopyrightText: Copyright OpenControlPlane contributors.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: landscaper-service
description: Helm chart for landscaper as a service

type: application
version: v1.2.1
appVersion: v1.2.1
