name: Versioned Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # we need this to be able to push tags
  pull-requests: read

jobs:
  release_tag:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2
        id: app-token
        with:
          # required
          app-id: 1312871
          private-key: ${{ secrets.OPENMCP_CI_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive

      - name: Read and validate VERSION
        id: version
        run: |
          VERSION=$(cat ./VERSION)
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-dev(-[0-9a-f]*)?)?$ ]]; then
            echo "Invalid version format: $VERSION"
            exit 1
          fi
          echo "New version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Skip release if version is a dev version
        if: contains(env.version, '-dev')
        run: |
          echo "Skipping development version release: ${{ env.version }}"
          echo "SKIP=true" >> $GITHUB_ENV
          exit 0

      - name: Check if VERSION is already tagged
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ env.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.version }} already exists. Skipping release."
            echo "SKIP=true" >> $GITHUB_ENV
            exit 0
          fi
          echo "Tag ${{ env.version }} doesn't exists. Proceeding with release."

      - name: Create Git tag
        if: ${{ env.SKIP != 'true' }}
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo "Tagging as $AUTHOR_NAME <$AUTHOR_EMAIL>"
          
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=$AUTHOR_EMAIL" >> $GITHUB_ENV
          
          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          
          git tag -a "${{ env.version }}" -m "Release ${{ env.version }}"
          git push origin "${{ env.version }}"
          
          NESTED_GO_MODULES="integration-test"
          
          for MODULE in $NESTED_GO_MODULES; do
            git tag -a "${MODULE}/${{ env.version }}" -m "Release ${{ env.version }}"
            git push origin "${MODULE}/${{ env.version }}"
          done

      - name: Create GitHub release
        if: ${{ env.SKIP != 'true' }}
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
          body: ""
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push dev VERSION
        if: ${{ env.SKIP != 'true' }}
        run: |
          echo "${{ env.version }}-dev" > VERSION
                    
          git config user.name "${{ env.AUTHOR_NAME }}"
          git config user.email "${{ env.AUTHOR_EMAIL }}"
          git add VERSION
          git add go.mod
          git add integration-test/go.mod
          
          git commit -m "chore(release): Update VERSION to ${{ env.version }}-dev"
          git push origin main
